from .app import app, db
from .models import Produit

@app.cli.command()
def init_db():
    """
    Initialiser la base de données.
    """
    db.drop_all()
    db.create_all()
    db.session.add(Produit("REF-001", "Bois", "Point P", 1))
    db.session.add(Produit("REF-002", "Verre", "Point P", 10))
    db.session.add(Produit("REF-003", "Sable", "Point P", 20))
    db.session.add(Produit("REF-004", "Ciment", "Point P", 1))
    db.session.add(Produit("REF-005", "Terre", "Point P", 50))
    db.session.add(Produit("REF-006", "Plastique", "Point P", 100))
    db.session.add(Produit("REF-007", "PVC", "Point P", 5))
    db.session.add(Produit("REF-008", "Beton", "Point P", 15))
    db.session.add(Produit("REF-009", "Fer", "Point P", 1))
    db.session.add(Produit("REF-010", "Aluminium", "Point P", 3))
    db.session.add(Produit("REF-011", "Pot", "Point P", 18))
    db.session.add(Produit("REF-012", "Pierre", "Leroy Merlin", 1))
    db.session.add(Produit("REF-013", "Granite", "Leroy Merlin", 25))
    db.session.add(Produit("REF-014", "Marbre", "Leroy Merlin", 1))
    db.session.add(Produit("REF-015", "Carrelage", "Saint-Gobain", 50))
    db.session.add(Produit("REF-016", "Parquet chêne", "Leroy Merlin", 20))
    db.session.add(Produit("REF-017", "Gypse", "Point P", 100))
    db.session.add(Produit("REF-018", "Ardoise", "Castorama", 30))
    db.session.add(Produit("REF-019", "Tuile rouge", "Point P", 200))
    db.session.add(Produit("REF-020", "Brique", "Brico Dépôt", 500))
    db.session.add(Produit("REF-021", "Laine de verre", "Isover", 15))
    db.session.add(Produit("REF-022", "Polystyrène", "Knauf", 25))
    db.session.add(Produit("REF-023", "Acier", "ArcelorMittal", 5))
    db.session.add(Produit("REF-024", "Cuivre", "Nexans", 2))
    db.session.add(Produit("REF-025", "Zinc", "Vieille Montagne", 3))
    db.session.add(Produit("REF-026", "Peinture blanche", "Dulux Valentine", 10))
    db.session.add(Produit("REF-027", "Vernis bois", "V33", 8))
    db.session.add(Produit("REF-028", "Colle carrelage", "Weber", 12))
    db.session.add(Produit("REF-029", "Joint silicone", "Rubson", 40))
    db.session.add(Produit("REF-030", "Vis à bois", "Wurth", 1000))
    db.session.commit()
    print("Base de données initialisée !")